### PR TITLE
Enable delta Eddington shortwave scheme in GEOS

### PR DESCRIPTION
**Pull request by zhaobin74**
This PR turned on `delta-Eddington` shortwave scheme in GEOS-ESM. Some users need this option to be consistent with other centers.

To use `delta-Eddington` scheme, set the following in `ice_in`
```
&shortwave_nml
    shortwave   =  'dEdd'
```

Default is still `ccsm3` until `dEdd` is fully vetted.

### CODE REVIEW

**Review by mathomp4 — APPROVED** [review]
Trust in @zhaobin74 !

**Comment by zhaobin74** [comment]
> Trust in @zhaobin74 !

thanks, @mathomp4.

Do you know why GHactions reported 2 failings? i couldn't find which 2 cases failed from the log.

**Comment by mathomp4** [comment]
> > Trust in @zhaobin74 !
> 
> thanks, @mathomp4.
> 
> Do you know why GHactions reported 2 failings? i couldn't find which 2 cases failed from the log.

Looks like these ones:
```
PASS conda_macos_restart_col_1x1_debug_ionetcdf build
FAIL conda_macos_restart_col_1x1_debug_ionetcdf run
FAIL conda_macos_restart_col_1x1_debug_ionetcdf test 
```
Not sure how to read that.

**Comment by zhaobin74** [comment]
> > > Trust in @zhaobin74 !
> > 
> > 
> > thanks, @mathomp4.
> > Do you know why GHactions reported 2 failings? i couldn't find which 2 cases failed from the log.
> 
> Looks like these ones:
> 
> ```
> PASS conda_macos_restart_col_1x1_debug_ionetcdf build
> FAIL conda_macos_restart_col_1x1_debug_ionetcdf run
> FAIL conda_macos_restart_col_1x1_debug_ionetcdf test 
> ```
> 
> Not sure how to read that.

Thanks, @mathomp4. Does 'macos' mean it is testing on MAC OS?

**Comment by mathomp4** [comment]
Yep. And I'm honestly not sure how your PR could have caused any issue. I mean, it's essentially blank code without the ifdef. 

And it looks like mothership Icepack hasn't changed the GitHub actions in a while. I'm going to re-run the job to see if it's consistent.

**Comment by mathomp4** [comment]
Same failures. @zhaobin74 you might need to reach out to the CICE folks to figure out why.

**Pull request merged**
